version: '3.0'

services:
  web:
    build: .
    image: bilinho
    container_name: bilinho
    restart: "no"
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASS
      - DB_DEV
      - DB_TEST
    ports:
      - 3000:3000
    volumes:
      - .:/bilinho
    depends_on:
      - db

  db:
    image: postgres
    restart: "no"
    ports:
      - 5429:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - data:/var/lib/postgresql/data/

volumes:
  data:
