version: '3.0'

services:
  web:
    build: .
    image: bilinho
    restart: "no"
    environment:
      - DBHOST
      - DBUSER
      - DBPASS
      - DEVDB
      - TESTDB
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres
    restart: "no"
    ports:
      - 5432:5432
    environment:
      - DEVDB
      - DBUSER
      - DBPASS
    volumes:
      - postgresdb:/var/lib/postgresql/data/

volumes:
  postgresdb:
