version: '3.0'

services:
  web:
    build: .
    image: bilinho
    restart: "no"
    environment:
      DBHOST: "${DBHOST}"
      DBUSER: "${DBUSER}"
      DBPASS: "${DBPASS}"
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres
    restart: "no"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "${DEVDB}"
      POSTGRES_USER: "${DBUSER}"
      POSTGRES_PASSWORD: "${DBPASS}"
    volumes:
      - postgresdb:/var/lib/postgresql/data/

volumes:
  postgresdb:
